Wrath Classic Phase 4 Update & Fixes
Hoizame/AtlasLootClassic pull request #398
Opened 2023-10-10 13:10 UTC by Anyalah

Includes Timothy-Page Mount API Changes

- Add Defiler's Scourgestone Vendor
- Update Dalaran Vendor Rings/Gems
- #397, #388 Update to use new Mount API 
- #396 Added "Maiden of Grief" Missing items in Titan Rune Beta - Halls of Stone
- #395 Fixed "King Dred" Wrong loot in Titan Rune Beta - Drak'Tharon Keep
- #394 Fixed "The Prophet Tharon'ja" Wrong loot in Titan Rune Beta - Drak'Tharon Keep
- #393 Added Missing Leatherworking Fur Linings
- #391 Added Enchanting Cloak Resistances (Arcane, Fire, Frost, Nature, Shadow), Removed Duplicates
- #387 Fixed Incorrect Set Links for Death Knight Season 7 PvP Set  
- #381 Added "Six Shared Loot Bosses" Missing items in Titan Rune Beta - Violet Hold

2023-10-11 02:53 UTC, jazminite commented
works for me, thanks! <3

2023-10-11 10:02 UTC, leehmanQQ commented
yep works for me as well

2023-10-11 11:47 UTC, Remsslk commented
Tysm <3

2023-10-11 14:29 UTC, Anyalah commented
I have created a [release](https://github.com/Anyalah/AtlasLootClassic/releases/tag/v3.4.3.pre-release) here which has a direct download link until Hoizame can update
[Direct Download Link](https://github.com/Anyalah/AtlasLootClassic/releases/download/v3.4.3.pre-release/AtlasLootClassic_Phase4.zip)

2023-10-11 17:51 UTC, mykkenny commented
Is there any way to prevent the "AtlasLoot-Dev: Player 'PlayerName-Server' sends version '3010003'!" message being spammed when using this release?

2023-10-11 18:06 UTC, bferg317 commented
Running this release just fine

2023-10-12 15:13 UTC, jakobbsm commented on .vs/slnx.sqlite
It seems this configuration file snuck itself in. Might wanna check out this .gitignore for VS Code.
https://github.com/github/gitignore/blob/main/Global/VisualStudioCode.gitignore

2023-10-12 19:44 UTC, bferg317 commented on .vs/slnx.sqlite
Definitely a good suggestion. By default my .gitignores always have these:
```
# OS Junk. Currently only Windows stuff: thumbnailer db and temp files.
**thumbs.db
~*

# IDE Junk. Currently only VSCode stuff.
.VSCode
.vscode
*.code-workspace
*.code-project
```

2023-10-13 03:08 UTC, BIIMSDev commented
> Is there any way to prevent the "AtlasLoot-Dev: Player 'PlayerName-Server' sends version '3010003'!" message being spammed when using this release?

@mykkenny

hi, 
It was temporarily fixed.
Alarms are no longer displayed.
Test complete!

download link :) 
[https://drive.google.com/file/d/1xBvM7kd20Lb2I0wlhOqdZ3saQtyR3Uen/view?usp=sharing](url)

2023-10-14 16:41 UTC, ssateneth commented
Can you please add #400 and #411

2023-10-14 21:58 UTC, Barov2 requested changes

2023-10-14 21:58 UTC, Barov2 commented on AtlasLootClassic/AtlasLootClassic_Wrath.toc
> +﻿## Interface: 30404
```suggestion
﻿## Interface: 30403
```

2023-10-14 21:58 UTC, Barov2 commented on AtlasLootClassic_DungeonsAndRaids/data-wrath.lua
> +				{ 19, 43102 }, -- Frozen Orb { 21, 41796 }, -- Design: Infused Twilight Opal
```suggestion
 				{ 19, 43102 }, -- Frozen Orb
 				{ 21, 41795 }, -- Design: Timeless Forest Emerald
```

2023-10-14 21:58 UTC, Barov2 commented on AtlasLootClassic_DungeonsAndRaids/data-wrath.lua
> +				{ 23, "ac1860" }, { 101, 40616 }, -- Helm of the Lost Conqueror
```suggestion
				{ 23, "ac1860" },
				{ 101, 40616 }, -- Helm of the Lost Conqueror 
```

2023-10-15 09:41 UTC, saimpot commented
Hey @Anyalah and @Timothy-Page, I tried this PR and I have a feeling that because of a massive update that it's trying to do somewhere either it's sending amount of data to a huge number of clients, or receiving, it's cause crazy lag spikes every 40-60 or so seconds. 

I haven't been able to pinpoint this, but I had a ping running to google.com with constant 34ms while doing dungeons, and was getting these crazy lag spikes, and no other connection problems. As soon as I deleted this, it was gone.

I know it's kinda anecdotal evidence,  but maybe someone else had the same issue or you have an idea on what's happening.

2023-10-15 09:54 UTC, BjarkeM commented
> Hey @Anyalah and @Timothy-Page, I tried this PR and I have a feeling that because of a massive update that it's trying to do somewhere either it's sending amount of data to a huge number of clients, or receiving, it's cause crazy lag spikes every 40-60 or so seconds.
> 
> I haven't been able to pinpoint this, but I had a ping running to google.com with constant 34ms while doing dungeons, and was getting these crazy lag spikes, and no other connection problems. As soon as I deleted this, it was gone.
> 
> I know it's kinda anecdotal evidence, but maybe someone else had the same issue or you have an idea on what's happening.

It's completely unrelated, none of the changes here would do that.

2023-10-15 12:40 UTC, saimpot commented
> > Hey @Anyalah and @Timothy-Page, I tried this PR and I have a feeling that because of a massive update that it's trying to do somewhere either it's sending amount of data to a huge number of clients, or receiving, it's cause crazy lag spikes every 40-60 or so seconds.
> > I haven't been able to pinpoint this, but I had a ping running to google.com with constant 34ms while doing dungeons, and was getting these crazy lag spikes, and no other connection problems. As soon as I deleted this, it was gone.
> > I know it's kinda anecdotal evidence, but maybe someone else had the same issue or you have an idea on what's happening.
> 
> It's completely unrelated, none of the changes here would do that.

Are you sure? Not even the broadcast thing that prints to the chat "AtlasLoot-Dev: Player 'PlayerName-Server' sends version '3010003'!" message delete Ver"?

2023-10-15 22:20 UTC, Timothy-Page commented
@saimpot I have not reviewed the code that Anyalah updated but the code I changed is also used in my add "Wrath Random Mounter" and is called everytime the zone name next to the mini map changes and it is not causing issues.

2023-10-16 06:22 UTC, saimpot commented
> @saimpot I have not reviewed the code that Anyalah updated but the code I changed is also used in my add "Wrath Random Mounter" and is called everytime the zone name next to the mini map changes and it is not causing issues.

That's good to hear, I'll start using this again then and see if I notice anything weird. Thank you for the update and for the work that you do! Both of you!

2023-10-17 11:40 UTC, repsejnworb commented
@Hoizame any ETA on merging?

2023-10-17 16:55 UTC, andreasgottwald commented
> > > Hey @Anyalah and @Timothy-Page, I tried this PR and I have a feeling that because of a massive update that it's trying to do somewhere either it's sending amount of data to a huge number of clients, or receiving, it's cause crazy lag spikes every 40-60 or so seconds.
> > > I haven't been able to pinpoint this, but I had a ping running to google.com with constant 34ms while doing dungeons, and was getting these crazy lag spikes, and no other connection problems. As soon as I deleted this, it was gone.
> > > I know it's kinda anecdotal evidence, but maybe someone else had the same issue or you have an idea on what's happening.
> > 
> > 
> > It's completely unrelated, none of the changes here would do that.
> 
> Are you sure? Not even the broadcast thing that prints to the chat "AtlasLoot-Dev: Player 'PlayerName-Server' sends version '3010003'!" message delete Ver"?

It's normal if you have a dev-version - you can disable it by commenting out the atlasloot.lua line 60:

function AtlasLoot:DevPrint(msg)
	if AtlasLoot.IsDevVersion then
		-- print("|cff33ff99AtlasLoot-Dev|r: "..(msg or ""))
	end
end

2023-10-17 23:11 UTC, MyTechnoHunter commented
> > > > Hey @Anyalah and @Timothy-Page, I tried this PR and I have a feeling that because of a massive update that it's trying to do somewhere either it's sending amount of data to a huge number of clients, or receiving, it's cause crazy lag spikes every 40-60 or so seconds.
> > > > I haven't been able to pinpoint this, but I had a ping running to google.com with constant 34ms while doing dungeons, and was getting these crazy lag spikes, and no other connection problems. As soon as I deleted this, it was gone.
> > > > I know it's kinda anecdotal evidence, but maybe someone else had the same issue or you have an idea on what's happening.
> > > 
> > > 
> > > It's completely unrelated, none of the changes here would do that.
> > 
> > 
> > Are you sure? Not even the broadcast thing that prints to the chat "AtlasLoot-Dev: Player 'PlayerName-Server' sends version '3010003'!" message delete Ver"?
> 
> It's normal if you have a dev-version - you can disable it by commenting out the atlasloot.lua line 60:
> 
> function AtlasLoot:DevPrint(msg) if AtlasLoot.IsDevVersion then -- print("|cff33ff99AtlasLoot-Dev|r: "..(msg or "")) end end

open the toc files, change from ## Version: @project-version@ to a real version number.. the code checks for the contents of that field and if found changes to a string with -dev.. which enables the dev print

if needed just use the older version number ## Version: v3.1.3

2023-10-22 14:11 UTC, merged